services:
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-martin34}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - app

  php:
    user: "${UID:-1000}:${GID:-1000}"
    build:
      context: ./back-sanremo/php
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./back-sanremo:/var/www/html
    networks:
      - app
    depends_on:
      - database


  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./back-sanremo:/var/www/html
      - ./front-sanremo/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./front-sanremo/build:/app
    networks:
      - app
    depends_on:
      - php
      - database
      - mercure


###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Uncomment the following line to disable HTTPS,
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.iHLdpAEjX4BqCsHJEegxRmO-Y6sMxXwNATrQyRNt3GY'
      MERCURE_SUBSCRIBER_JWT_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.iHLdpAEjX4BqCsHJEegxRmO-Y6sMxXwNATrQyRNt3GY'
      # Set the URL of your Symfony project (without trailing slash!) as value of the cors_origins directive
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://localhost:3000
        use_forwarded_headers "1"
        anonymous "false"
    # Comment the following line to disable the development mode
#    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    volumes:
      - mercure_data:/data
      - mercure_config:/config
    networks:
      - app
###< symfony/mercure-bundle ###

#
#  frontend:
#    build:
#      context: ./front-sanremo
#      dockerfile: Dockerfile
#    ports:
#      - '3000:3000'
#    volumes:
#      - ./front-sanremo/:/app
#    networks:
#      - app

volumes:
  database_data:

###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
###< symfony/mercure-bundle ###


networks:
  app:
